name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: |
          bun install --cwd frontend
          bun install --cwd backend

      - name: Run Prettier on Frontend
        run: bun prettier --write .
        working-directory: ./frontend

      - name: Run Prettier on Backend
        run: bun prettier --write .
        working-directory: ./backend

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Frontend Dependencies
        run: bun install
        working-directory: ./frontend
      - name: Build Frontend
        run: bun run build
        working-directory: ./frontend

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Backend Dependencies
        run: bun install
        working-directory: ./backend